# Generated by Django 2.2.2 on 2019-06-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='signatureCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
