# Generated by Django 2.2.17 on 2020-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prekey',
            name='unique_keyId',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='identityKey',
            new_name='identity_key',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='registrationId',
            new_name='registration_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='senderAddress',
            new_name='sender_address',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='senderRegistrationId',
            new_name='sender_registration_id',
        ),
        migrations.RenameField(
            model_name='prekey',
            old_name='keyId',
            new_name='key_id',
        ),
        migrations.RenameField(
            model_name='prekey',
            old_name='publicKey',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='signedprekey',
            old_name='keyId',
            new_name='key_id',
        ),
        migrations.RenameField(
            model_name='signedprekey',
            old_name='publicKey',
            new_name='public_key',
        ),
        migrations.AddConstraint(
            model_name='prekey',
            constraint=models.UniqueConstraint(fields=('device', 'key_id'), name='unique_key_id'),
        ),
    ]
