# Generated by Django 2.2.2 on 2019-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_signaturecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='signatureCount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
