# Generated by Django 2.2.2 on 2019-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190616_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prekey',
            name='keyId',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='signedprekey',
            name='keyId',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
