# Generated by Django 2.2.2 on 2019-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190621_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prekey',
            unique_together={('device', 'keyId')},
        ),
        migrations.AlterUniqueTogether(
            name='signedprekey',
            unique_together={('device', 'keyId')},
        ),
    ]
