# Generated by Django 2.2.2 on 2019-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190621_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prekey',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='signedprekey',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prekey',
            constraint=models.UniqueConstraint(fields=('device', 'keyId'), name='unique_keyId'),
        ),
        migrations.AddConstraint(
            model_name='signedprekey',
            constraint=models.UniqueConstraint(fields=('device', 'keyId'), name='unique_keyId'),
        ),
    ]
