# Generated by Django 2.2.2 on 2019-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190621_1438'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signedprekey',
            name='unique_keyId',
        ),
    ]
