# Generated by Django 2.2.2 on 2019-06-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190622_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prekey',
            name='keyId',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='signedprekey',
            name='keyId',
            field=models.PositiveIntegerField(),
        ),
    ]
