# Generated by Django 2.2.2 on 2019-07-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190622_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='signatureCount',
        ),
    ]
