# Generated by Django 2.2.4 on 2020-11-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_device_signaturecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='signingKey',
        ),
    ]
